### ISSUE TITLE
Problem opening /dev/lirc0

### ISSUE THREAD

**Issue by martin3000** [bengtmartensson/IrScrutinizer#492]
I have ubuntu 22.04 and IrScrutinizer AppImage 2.4.0
I go to the /dev/lirc tab, select /dev/lirc0 and press open. Then I get:

>Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: 'boolean 
org.harctoolbox.devslashlirc.Mode2LircDevice.canMeasureCarrier()'
        at org.harctoolbox.devslashlirc.Mode2LircDevice.canMeasureCarrier(Native Method)
	at org.harctoolbox.devslashlirc.Mode2LircDevice.toString(Mode2LircDevice.java:167)
	at org.harctoolbox.harchardware.ir.DevLirc.toString(DevLirc.java:300)
	at org.harctoolbox.guicomponents.DevLircBean.setProps(DevLircBean.java:153)
	at org.harctoolbox.guicomponents.DevLircBean.open(DevLircBean.java:210)
	at org.harctoolbox.guicomponents.HardwareBean.openClose(HardwareBean.java:99)

The strange thing is that I cannot find a reference of canMeasureCarrier in Mode2LircDevice.toString() !?

**Comment by bengtmartensson** [comment]
Sorry for that. Unfortunately, that version seems to use an erroneous version of the DevSlashLirc jar. It should work in the [current shapshot version](https://github.com/bengtmartensson/IrScrutinizer/releases/tag/ci-build), so please try that one.

**Comment by martin3000** [comment]
Thank you, that works!

**Comment by bengtmartensson** [comment]
Thank you for the report. I have tagged it as "not a bug" since it is no source code bug, but was a silly build from my side. (Built with a non-checked in. experimental DevSlashLirc).
